DATA:
  data_name: modelnet40 
  data_root: 'dataset/modelnet40ply2048'  # Fill in the pre-processed data path (which contains the .npy files)
  classes: 40
  fea_dim: 3
  loop: 30

TRAIN:
  net: cdformer_cls 
  stem_transformer: True
  use_xyz: True
  sync_bn: True  # adopt sync_bn or not
  cutmix_prob: 0.9
  downsample_scale: 4
  num_points: 1024 
  num_sample_points: 1200 
  num_layers: 4 
  depths: [1,1,3,1] 
  channels: [64,128,256,512]
  num_heads: [4,8,16,32]
  up_k: 3
  drop_path_rate: 0.3
  concat_xyz: False
  grid_size: 0.02
  max_batch_points: 640000
  max_num_neighbors: 34 # For KPConv
  ratio: 0.25
  k: [[8,8,8],[8,8,8],[8,8,8],[8,8,8]]

  # training
  aug: True
  wandb: False
  transformer_lr_scale: 0.1
  jitter_sigma: 0.005
  jitter_clip: 0.02
  scale_ratio: 0.5
  drop_ratio: 0.5
  rotate_along_z: False
  scheduler_update: step 
  scheduler: Cosine
  power: 2.0
  warmup: linear
  warmup_iters: 1500
  warmup_ratio: 0.000001
  warmup_epochs: 2
  warmup_gamma: 0.5
  warmup_cycle_ratio: 0.5
  use_amp: True
  optimizer: AdamW 
  ignore_label: 255
  label_smoothing: 0.3
  train_gpu: [0]
  workers: 8  # data loader workers
  batch_size: 32  # batch size for training
  batch_size_val: 8  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.001
  epochs: 600
  milestones: [360, 480]
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.05
  drop_rate: 0.5
  manual_seed: 
  print_freq: 10
  save_freq: 1
  save_path: output/modelnet40/cdformer/
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
  train_split: train
  clip_grad_norm: 10.0
  debug: 1
Distributed:
  multi_node: 0
  dist_url: tcp://localhost:8888
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_split: test  # split in [train, val and test]
  test_gpu: [0]
  test_workers: 8
  batch_size_test: 8
  model_path: # Fill the path of the trained .pth file model
  save_folder: # Fill the path to store the .npy files for each scene
